### ISSUE TITLE
investigate this

### ISSUE THREAD

**Issue by philihp** [philihp/score#19]
before...
aaron: { mu: 17.408, sigma: 5.389 }
ken: { mu: 33.779, sigma: 4.906 }
adam: { mu: 14.812, sigma: 5.994 }
jenn: { mu: 28.674, sigma: 8.132 }

after... 53bbea995f9da4fdb4005124a7598b86d61c4c45
aaron: { mu: 15.675, sigma: 5.322 }
ken: { mu: 33.702, sigma: 4.865 }
adam: { mu: 15.405, sigma: 5.898 }
jenn: { mu: 31.739, sigma: 7.994 }

**Comment by aarondixon** [comment]
Another oddity: with only one match played (tmars), the ranking doesn't match the results of the game:

GAME RESULTS
Eric 62
Matt 57
Aaron 56
Adam 55
Ken 51

RANKING
1	adam	2.795	27.667	68.733
2	ken	2.113	26.833	67.900
3	aaron	1.182	25.722	66.912
4	matt	-0.280	24.056	65.801
5	eric	-3.613	20.722	65.801

**Comment by philihp** [comment]
RE first instance... should have been different:

> a
{ mu: 17.408, sigma: 5.389 }
> b
{ mu: 33.779, sigma: 4.906 }
> c
{ mu: 14.812, sigma: 5.994 }
> d
{ mu: 28.674, sigma: 8.132 }
>
>
>
> let [[ w],[x],[y],[z] ] = rate([[a],[b],[c],[d]])
undefined
> w
{ mu: 19.06665739605397, sigma: 5.37353333679219 }
> x
{ mu: 33.8897269980001, sigma: 4.863219619462103 }
> y
{ mu: 15.898952504431042, sigma: 5.910736425389025 }
> z
{ mu: 22.592226614031976, sigma: 7.701672339692088 }
